name: Testing action when closing PR

on:
    pull_request:
        types: [closed]

jobs:
    hasOneOfLabel:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Labeled to preview
              id: haslabel
              uses: DanielTamkin/HasLabel@v1.0.4
              with:
                  contains: "preview"
